name: Build and Push Docker Image with OCI Labels and Attestation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: nmane-crest
        password: ${{ secrets.MY_PAT }}

    - name: Build and push Docker Image 1 (with OCI Label)
      uses: docker/build-push-action@v3
      with:
        context: .
        file: .github/workflows/Dockerfile
        push: true
        tags: ghcr.io/packageghcr/test-ghcr-public:image1-latest
        labels: org.opencontainers.image.source=https://bitbucket.org/nikhilmane_crest/new_project/src/master/

    - name: Build and push Docker Image 2 (with Attestation)
      run: |
        docker buildx build --provenance=true --tag ghcr.io/packageghcr/test-ghcr-public:image2-latest --push -f .github/workflows/Dockerfile .
