# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Add an OCI label to the image with the repository URL
LABEL org.opencontainers.image.source="https://bitbucket.org/nikhilmane_crest/new_project/src/master/"

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World


# Instead, just run a simple Python command
CMD ["python", "-c", "print('Hello, World!')"]
